export enum AppRoutes {
  Homepage = '/',
  Dashboard = '/dashboard',
  Login = '/login',
  Signup = '/signup',
  ForgotPassword = '/forgot-password',
  ResetPassword = '/reset-password/:resetToken',
  Payment = '/payment',
  Settings = '/settings',
  PaymentSuccess = '/payment/success',
  Chatbot = '/ai-chatbot',
  Pricing = '/pricing',
  QuizBuilder = '/quiz-builder',
  QuickNotes = '/quick-notes',
  LectureSummarizer = '/lecture-summarizer',
}
